function this = addBarrier(this, Options, iteration, nOutput, bounds)
    if (~strcmp(Options.barrier, 'none'))
        if (nOutput == 1)
            this.curJ = DELOS.barrierFunction(...
                this.curJ, this.curG, this.curPar, ...
                bounds, ...
                iteration, ...
                Options.maxIter, ...
                Options.barrier);
        elseif (nOutput == 2)
            [this.curJ, this.curG] = DELOS.barrierFunction(...
                this.curJ, this.curG, this.curPar, ...
                bounds, ...
                iteration, ...
                Options.maxIter, ...
                Options.barrier);
        else
            error('Call to objective function with too many outputs!');
        end
    end
end